android.useAndroidX=true
# 💡 আগেরটি ভুল ছিল: android.experimental.alloworg.jetbrains.kotlin.jvm.gradle.plugin=true
android.experimental.allow.org.jetbrains.kotlin.jvm.gradle.plugin=true

android.defaults.buildfeatures.buildconfig=true
android.suppressUnsupportedCompileSdk=36
android.nonTransitiveRClass=false

# Gradle JVM Heap Memory
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+UseG1GC
kotlin.daemon.jvmargs=-Xmx1024m

# Parallel build & caching
org.gradle.parallel=true
org.gradle.caching=true

android.experimental.art-profiles.enable=false
android.newDsl=false