name: Flutter Build Release AAB

on:
  push:
    branches:
      - main # আপনার মেইন ব্রাঞ্চের নাম যদি master হয়, তবে এখানে master লিখে দেবেন

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Java
        uses: actions/setup-java@v4.7.0
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/upload-keystore.jks

      - name: Create key.properties
        run: |
          cat <<EOF > android/key.properties
          keyAlias=${{ secrets.KEY_ALIAS }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          storeFile=upload-keystore.jks
          storePassword=${{ secrets.STORE_PASSWORD }}
          EOF

      - name: Build AAB
        env:
          GRADLE_OPTS: "-Xmx4096m -XX:MaxMetaspaceSize=1024m"
        run: flutter build appbundle --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.6.1
        with:
          name: app-release
          path: build/app/outputs/bundle/release/app-release.aab